### ISSUE TITLE
pip failed to install rpi zero w

### ISSUE THREAD

**Issue by limitless808** [jarvin521/all-sport-scoreboard#1]
Currently using a rpi zero w (not sure if that matters).

While following the readme guide, I ran into several errors while installing.

First was rgbmatrix and the second was json. errors returned are as follows

pip install rgbmatrix
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement rgbmatrix
ERROR: No matching distribution found for rgbmatrix

pip install json
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement json
ERROR: No matching distribution found for json

when running the python command just to test, I get this

sudo python main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=20 --led-slowdown-gpio=4
Traceback (most recent call last):
  File "/home/pi/nfl-led-scoreboard/main.py", line 2, in <module>
    from data.scoreboard_config import ScoreboardConfig
  File "/home/pi/nfl-led-scoreboard/data/scoreboard_config.py", line 1, in <module>
    from utils import get_file
  File "/home/pi/nfl-led-scoreboard/utils.py", line 1, in <module>
    from rgbmatrix import RGBMatrixOptions, graphics
ModuleNotFoundError: No module named 'rgbmatrix'

are there  any other sources for install? also, no  files have  been modified, and  this was installed on a fresh copy of raspbian lite x86

**Comment by jarvin521** [comment]
I think I had my README wrong.  I just forked it from here and updated it in place: https://github.com/mikemountain/nfl-led-scoreboard

Looks like you probably cloned his repo and not this one.  Try it again with this repo.

If that doesn't work then I'll have to take a closer look when I get a chance.  You definitely need rgbmatrix and json installed with PIP or this will never work.

**Comment by jarvin521** [comment]
Looks like maybe you don't need to pip install json... its built-in to python.  So, if you clone the right repo I think it should work.  Good luck!

**Comment by limitless808** [comment]
Works like a charm! I meant to  reply earlier, but  time escaped me. Thank you. I will be looking at your NFL script next as well.

**Comment by jarvin521** [comment]
Glad to hear it!  The NFL script is just this one.  I created a new repo once I had it polished a little bit.  If you want just NFL look at Mike mountain's https://github.com/mikemountain/nfl-led-scoreboard

His code is what this one is based off of
